export const negatives = [
    "problem",
    "unfriendly",
    "horrible",
    "stue",
    "unsupported",
    "average",
    "dirty",
    "negative",
    "unsupported",
    "hell",
    "bad",
    "didn't work",
    "ancient",
    "cold",
    "tiny",
    "small",
    "hard",
    "uncomfortable",
    "torn",
    "Stay away",
    "old",
    "decrepit",
    "terrible",
    "broken",
    "junk",
    "awful",
    "worst",
    "disgusting",
    "falling out",
    "minty",
    "thin",
    "nightmare",
    "freezing",
    "didn't sleep",
    "rude",
    "undisciplined",
    "fell off",
    "rotten",
    "mess",
    "surly",
    "never",
    "not going to come back"
];

export const positives = [
    'great',
    'good',
    'very nice',
    'amazing',
    'careful',
    'well',
    'helpful',
    'friendly',
    'clean',
    'cleanliness',
    'easy',
    'excellent',
    'top',
    'superb',
    'fantastic',
    'best',
    'comfortable',
    'perfect',
    'love',
    'going to come back',
    'made our stay',
    'was fun',
    'not far from',
];